import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/global/Header";
import Footer from "@/app/components/global/Footer";
import { getHeaderData } from '@/app/actions/cms';

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  display: "swap",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Kieren McGill",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const headerData = await getHeaderData();

  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} antialiased dark relative flex flex-col min-h-screen h-full`}
      >
        <Header headerData={headerData?.data ?? null} />
        <main className="flex flex-col flex-grow">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
